name: Build Aseprite (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Setup MSVC (VS2022)
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Download Skia m124 (Windows prebuilt)
      run: |
        curl -L -o skia.zip https://github.com/aseprite/skia/releases/download/m124-0/skia-windows-Release-x64.zip
        mkdir skia
        tar -xf skia.zip -C skia

    - name: Configure CMake
      run: |
        cmake `
          -B build `
          -D CMAKE_BUILD_TYPE=RelWithDebInfo `
          -D ENABLE_UPDATER=OFF `
          -D ENABLE_TELEMETRY=OFF `
          -D SKIA_DIR=skia `
          -G Ninja

    - name: Build
      run: cmake --build build --target aseprite

    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-windows
        path: build/bin/aseprite.exe

